---
sudo: required

language: cpp

os:
  - linux
compiler:
  - gcc
env:
  - CONFIGURE_OPTIONS=--disable-shared
  - CONFIGURE_OPTIONS=
matrix:
  include:
    - os: osx
      env: HOST=arm-apple-darwin

before_install:
  - if test x"$MEVAL" != x; then eval ${MEVAL}; fi

install:
  - ./.travis/install.sh

script:
  - if ! test x"$MEVAL" = x; then eval ${MEVAL}; fi
  - ./.travis/build.sh
